FROM mcr.microsoft.com/vscode/devcontainers/miniconda:latest

# Set the default shell to bash instead of sh
SHELL ["/bin/bash", "-c"]

# Add activation of conda base environment to ~/.bashrc
RUN echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/vscode/.bashrc && \
    echo "conda activate base" >> /home/vscode/.bashrc

# Copy environment.yml (if found) to a temp location so we update the environment. Also
# copy "noop.txt" so the COPY instruction does not fail if no environment.yml exists.
COPY environment.yml* .devcontainer/noop.txt /tmp/conda-tmp/
RUN if [ -f "/tmp/conda-tmp/environment.yml" ]; then umask 0002 && /opt/conda/bin/conda env update -n base -f /tmp/conda-tmp/environment.yml; fi \
    && rm -rf /tmp/conda-tmp
